app/src/main/java/org/openmrs/android/fhir/MainActivity.kt
app/src/main/java/org/openmrs/android/fhir/adapters/LocationAdapter.kt
app/src/main/java/org/openmrs/android/fhir/data/PreferenceKeys.kt
app/src/main/java/org/openmrs/android/fhir/data/TimestampBasedDownloadWorkManagerImpl.kt
app/src/main/java/org/openmrs/android/fhir/fragments/AddPatientFragment.kt
app/src/main/java/org/openmrs/android/fhir/fragments/HomeFragment.kt
app/src/main/java/org/openmrs/android/fhir/fragments/LocationFragment.kt
app/src/main/java/org/openmrs/android/fhir/fragments/PatientListFragment.kt
app/src/main/java/org/openmrs/android/fhir/viewmodel/AddPatientViewModel.kt
app/src/main/java/org/openmrs/android/fhir/viewmodel/LocationViewModel.kt
app/src/main/res/drawable/ic_arrow_drop_down_24.xml
app/src/main/res/drawable/ic_location.xml
app/src/main/res/drawable/ic_location_small.xml
app/src/main/res/layout/add_patient_fragment.xml
app/src/main/res/layout/fragment_home.xml
app/src/main/res/layout/fragment_location.xml
app/src/main/res/menu/drawer_menu.xml
app/src/main/res/navigation/reference_nav_graph.xml
app/src/main/res/values/strings.xml

- Added location resource to sync.
- Added location identifier to save patient resource.
- Added current location to Location Screen, Add Patient Screen & sidepane.
- Blocked patient registration w/o selecting location. 
cc: @icrc-jofrancisco , @icrc-fdeniger 
**Screenshots**

Integrate locations

---

app/src/main/java/org/openmrs/android/fhir/adapters/PatientItemViewHolder.kt
app/src/main/java/org/openmrs/android/fhir/viewmodel/PatientListViewModel.kt
app/src/main/res/layout/patient_list_item_view.xml

- replaced risk icon with sync icon

Integrate unsynced patient icon to PatientList

---

app/src/main/java/org/openmrs/android/fhir/fragments/PatientListFragment.kt

(fix) add Blocked and Cancelled states

(fix) add Blocked and Cancelled states

---

.github/.worklfow/build.yaml
.github/.worklfow/codeql.yaml
.github/action/commonSetup/action.yml
app/build.gradle.kts

add github actions

---

core/src/main/java/org/openmrs/android/fhir/auth/AuthConfiguration.kt

if discovery_uri is not set or blank ignore it.

if discovery url is empty or null , ignore it.

---

app/build.gradle.kts

fix security message by adding targetSdk = 34

---

core/src/main/java/org/openmrs/android/fhir/adapters/PatientDetailsRecyclerViewAdapter.kt
core/src/main/java/org/openmrs/android/fhir/viewmodel/PatientListViewModel.kt
core/src/main/res/layout/patient_details_header.xml
core/src/main/res/values/styles.xml

(feat) Dynamically display patient identifiers in patient file.

(feat) Dynamically display patient identifiers in patient file.

---

core/build.gradle.kts
core/src/main/java/org/openmrs/android/fhir/LoginRepository.kt
core/src/main/java/org/openmrs/android/fhir/SplashActivity.kt

fix nullpoint when the refresh token is null

---

core/src/main/java/org/openmrs/android/fhir/data/FhirSyncWorker.kt

(fix) Update upload strategy

---

core/src/main/java/org/openmrs/android/fhir/MainActivity.kt
core/src/main/java/org/openmrs/android/fhir/adapters/SyncSessionAdapter.kt
core/src/main/java/org/openmrs/android/fhir/adapters/SyncSessionItemViewHolder.kt
core/src/main/java/org/openmrs/android/fhir/data/database/Converters.kt
core/src/main/java/org/openmrs/android/fhir/data/database/Dao.kt
core/src/main/java/org/openmrs/android/fhir/data/database/model/SyncSession.kt
core/src/main/java/org/openmrs/android/fhir/di/AppComponent.kt
core/src/main/java/org/openmrs/android/fhir/di/ViewModelModule.kt
core/src/main/java/org/openmrs/android/fhir/extensions/Utils.kt
core/src/main/java/org/openmrs/android/fhir/fragments/PatientListFragment.kt
core/src/main/java/org/openmrs/android/fhir/fragments/SyncInfoFragment.kt
core/src/main/java/org/openmrs/android/fhir/viewmodel/MainActivityViewModel.kt
core/src/main/java/org/openmrs/android/fhir/viewmodel/SyncInfoViewModel.kt
core/src/main/res/drawable/bg_delete_button.xml
core/src/main/res/drawable/bg_item_sync_session.xml
core/src/main/res/layout/fragment_home.xml
core/src/main/res/layout/fragment_patient_list.xml
core/src/main/res/layout/fragment_sync_info.xml
core/src/main/res/layout/item_sync_session.xml
core/src/main/res/navigation/reference_nav_graph.xml
core/src/main/res/values/colors.xml
core/src/main/res/values/strings.xml

- Integrating activity screen for sync information. 
Solves #68

Remove toasters integrate activity page

---

README.md
app/src/main/AndroidManifest.xml
app/src/main/res/values/server.xml
app/src/main/res/xml/file_paths.xml
core/src/main/java/org/openmrs/android/fhir/MainActivity.kt
core/src/main/java/org/openmrs/android/fhir/data/database/Dao.kt
core/src/main/java/org/openmrs/android/fhir/extensions/Utils.kt
core/src/main/java/org/openmrs/android/fhir/viewmodel/SyncInfoViewModel.kt
core/src/main/res/drawable/ic_diagnostics.xml
core/src/main/res/menu/drawer_menu.xml
core/src/main/res/values/server.xml
core/src/main/res/values/strings.xml

integrated application diagnostic tool in menu.

---

core/src/main/java/org/openmrs/android/fhir/adapters/SyncSessionItemViewHolder.kt
core/src/main/res/layout/item_sync_session.xml

Minor change to UI to be more in line with app theme.

(refactor) changed sync info to card view.

---

app/src/main/AndroidManifest.xml
core/build.gradle.kts
core/src/main/AndroidManifest.xml
core/src/main/res/xml/file_paths.xml

Fixes Github Build failure in pipeline.

Add AndroidManifest for core module

---

.github/workflows/build.yaml

sign aab files and create release

sign aab files and create release

---

.github/workflows/build.yaml

sign create apk dev

---

.github/workflows/build.yaml

sign apk dev

---

README.md

add documentation related to releases

---

core/src/main/assets/new-patient-registration-paginated.json

This pull request updates the patient registration schema by removing mandatory constraints from specific fields. The changes aim to improve flexibility during the patient registration process, accommodating scenarios where certain information may not be immediately available.
These changes are necessary to:
- Allow partial registrations when certain information is unavailable at the time of onboarding.
- Improve user experience by minimizing friction during data entry.
Thanks

(chore) Remove mandatory fields in registration schema

---

core/src/main/java/org/openmrs/android/fhir/fragments/GenericFormEntryFragment.kt
core/src/main/java/org/openmrs/android/fhir/viewmodel/GenericFormEntryViewModel.kt
core/src/main/res/values/strings.xml

added exception handling for opening questionnaire

---

core/src/main/assets/new-patient-registration-paginated.json
core/src/main/java/org/openmrs/android/fhir/data/remote/interceptor/AddCookiesInterceptor.kt

- added session url to cookie interceptor

Fix Patient creation issue on dev3.

---

README.md
app/src/main/res/values/server.xml
core/src/main/java/org/openmrs/android/fhir/fragments/AddPatientFragment.kt
core/src/main/java/org/openmrs/android/fhir/fragments/EditPatientFragment.kt
core/src/main/java/org/openmrs/android/fhir/fragments/PatientDetailsFragment.kt
core/src/main/java/org/openmrs/android/fhir/viewmodel/AddPatientViewModel.kt
core/src/main/java/org/openmrs/android/fhir/viewmodel/EditPatientViewModel.kt
core/src/main/res/navigation/reference_nav_graph.xml
core/src/main/res/values/server.xml
dev3-app/src/main/res/values/server.xml

- added config for registration questionnaire name.
cc: @icrc-jofrancisco Let me know if changes are required to config for `registration_questionnaire_name`

Integrate fetch patient registration schema or app default

---

core/src/main/java/org/openmrs/android/fhir/fragments/CreateEncountersFragment.kt
core/src/main/java/org/openmrs/android/fhir/fragments/GenericFormEntryFragment.kt
core/src/main/res/navigation/reference_nav_graph.xml

(fix) Questionnaire id argument

(fix) Questionnaire id argument

---

app/build.gradle.kts
app/src/main/res/values/server.xml
core/src/main/java/org/openmrs/android/fhir/fragments/AddPatientFragment.kt
core/src/main/java/org/openmrs/android/fhir/fragments/EditEncounterFragment.kt
core/src/main/java/org/openmrs/android/fhir/fragments/EditPatientFragment.kt
core/src/main/java/org/openmrs/android/fhir/fragments/GenericFormEntryFragment.kt
core/src/main/res/values/server.xml
core/src/main/res/values/styles.xml
dev3-app/build.gradle.kts
dev3-app/src/main/res/values/server.xml
local.properties.default

Integrated review mode for questionnaires.

---

app/src/main/AndroidManifest.xml
build.gradle.kts
core/src/main/java/org/openmrs/android/fhir/Constants.kt
core/src/main/java/org/openmrs/android/fhir/MainActivity.kt
core/src/main/java/org/openmrs/android/fhir/data/OpenMRSHelper.kt
core/src/main/java/org/openmrs/android/fhir/data/PreferenceKeys.kt
core/src/main/java/org/openmrs/android/fhir/data/RestApiManager.kt
core/src/main/java/org/openmrs/android/fhir/data/remote/model/ResponseWrapper.kt
core/src/main/java/org/openmrs/android/fhir/di/AppModule.kt
core/src/main/java/org/openmrs/android/fhir/fragments/GenericFormEntryFragment.kt
core/src/main/java/org/openmrs/android/fhir/fragments/LocationFragment.kt
core/src/main/java/org/openmrs/android/fhir/fragments/PatientDetailsFragment.kt
core/src/main/java/org/openmrs/android/fhir/fragments/SelectPatientListFragment.kt
core/src/main/java/org/openmrs/android/fhir/viewmodel/EditEncounterViewModel.kt
core/src/main/java/org/openmrs/android/fhir/viewmodel/GenericFormEntryViewModel.kt
core/src/main/java/org/openmrs/android/fhir/viewmodel/LocationViewModel.kt
core/src/main/java/org/openmrs/android/fhir/viewmodel/PatientDetailsViewModel.kt
dev3-app/src/main/AndroidManifest.xml

This PR cleans up the codebase by removing outdated mock user data and integrating the actual Provider for consistent user context management across the app.

(chore) remove mock data and implement user provider

---

core/src/main/java/org/openmrs/android/fhir/data/OpenMRSHelper.kt
core/src/main/java/org/openmrs/android/fhir/data/PreferenceKeys.kt
core/src/main/java/org/openmrs/android/fhir/data/RestApiManager.kt
core/src/main/java/org/openmrs/android/fhir/data/remote/model/ResponseWrapper.kt
core/src/main/java/org/openmrs/android/fhir/viewmodel/GenericFormEntryViewModel.kt

Corrected logic related to associating providers with encounters and visits.
Resolved edge cases where provider data was missing, incorrect, or not syncing properly.

(fix) encounter and visit provider

---

core/src/main/assets/new-patient-registration-paginated.json
core/src/main/java/org/openmrs/android/fhir/data/OpenMRSHelper.kt
core/src/main/java/org/openmrs/android/fhir/viewmodel/AddPatientViewModel.kt
core/src/main/java/org/openmrs/android/fhir/viewmodel/EditPatientViewModel.kt

This PR introduces support for users with unknown exact DOB by allowing input of an estimated age in years or months. 
Added logic to calculate an estimated DOB based on provided age (in years or months) relative to the current date.
Introduced a flag to indicate the DOB is system-estimated.

(feat) Support for unknown DOB

---

core/src/main/java/org/openmrs/android/fhir/extensions/Utils.kt
core/src/main/java/org/openmrs/android/fhir/viewmodel/EditEncounterViewModel.kt
core/src/main/java/org/openmrs/android/fhir/viewmodel/GenericFormEntryViewModel.kt

(fix) save date fields without time

(fix) save date fields without time
